### PR TITLE
Add skeleton of an FAQ

### PR DESCRIPTION
**Pull request by GaryGSC**
This is clearly incomplete, but I figure it's a starting point.

I copied over the questions I had already written up in #251, then added a question and answer in response to something from yesterday.

I'm putting questions in subheadings (`###`) so that they can be directly linked to, like [this](https://github.com/byu-oit/hw-fargate-api/blob/faq/doc/faq.md#what-do-i-do-with-these-dependabot-pull-requests-are-they-safe-to-merge-if-they-pass-ci).

### CODE REVIEW

**Review by blakemorgan — APPROVED** [review]

**Review by yoshutch — APPROVED** [review]

**Comment by jvisker** [comment]
Is this the best place to put the FAQ? Or should we just link somewhere else? Maybe a github repo that is just AWS FAQ? Just food for thought. I think it looks good for now.

**Review by jvisker — APPROVED** [review]

**Comment by GaryGSC** [comment]
@jvisker - Fair question. In theory, this is what the Discussions feature is for. Want to try that? I just enabled it on the repo.

**Comment by jvisker** [comment]
@GaryGSC Try discussing this there? Or add an FAQ there?

**Comment by GaryGSC** [comment]
I don't like the idea of a separate repo - I feel it'd increase fragmentation.

As for using Discussions, I don't think they get copied over when somebody uses the template. I think that was my initial reasoning for wanting to drop files in this repo. We could make the README link to discussions here.

**Comment by jvisker** [comment]
My concern with using this repo is just that it is a template that combines multiple concepts. It isn't the authority over those concepts. So postman tests for example are something that exist for both fargate and lambda.

**Comment by GaryGSC** [comment]
I dropped the new question in [a Discussion](https://github.com/byu-oit/hw-fargate-api/discussions/254).

**Comment by GaryGSC** [comment]
I guess we're closing this in favor of Discussions. We haven't gotten a whole lot of traction either way, but we also haven't gotten a whole lot of questions lately.

**Pull request closed without merging**
