### PR TITLE
Flatten TF module structure via `.tfvars`/`.tfbackend`

### PR DESCRIPTION
**Pull request by GaryGSC**
Using [`.tfvars`](https://developer.hashicorp.com/terraform/language/values/variables#variable-definitions-tfvars-files) and [`.tfbackend`](https://developer.hashicorp.com/terraform/language/settings/backends/configuration#partial-configuration) files, we can flatten our TF modules.

| Before | After |
| ------- | ------ |
| 82d1b3e4-9e8d-49cd-b573-4642ec7badbb | 37774ebc-685d-4ce6-9f19-81e3f7a18d4a |

### CODE REVIEW

**Comment by GaryGSC** [comment]
This module restructuring clobbers the existing state, but I don't really want to fill up the template with a bunch of [`moved` blocks](https://developer.hashicorp.com/terraform/language/modules/develop/refactoring#moved-block-syntax).

**Comment by GaryGSC** [comment]
As an example of how to use these environments, navigate to the `terraform/app` directory and then:
- `aws sso login`
- `terraform init -backend-config=dev.s3.tfbackend`
- `terraform plan -var-file=dev.tfvars`

---

If you then try switch to production (not that you should really be doing that outside of CI/CD), the CLI will instruct you to call `terraform init` with either the `-migrate-state` or `-reconfigure`. `-reconfigure` is the correct option here because you're not trying to migrate our dev state to prd. So, it'd look like:
- `aws sso login` (but to the prd account this time)
- `terraform init -backend-config=prd.s3.tfbackend -reconfigure`
- `terraform plan -var-file=prd.tfvars`

**Comment by GaryGSC** [comment]
Rebased on `dev`.

**Comment by stuft2** [comment]
@jvisker have we talk about this in the cloud guild yet? Are we still discussing it? Do we need to update an ADR before merging?

**Comment by GaryGSC** [comment]
Updated docs. That needed to happen.

Also renamed `terraform-iac/` to `terraform/`. We're restructuring our TF stuff anyways, so this seemed like a good opportunity to also rename the directory. Why? Calling the directory `terraform/` is common enough in the industry that themes can pick up on that (e.g. in [VSCode](https://github.com/PKief/vscode-material-icon-theme) or [Chrome](https://github.com/Claudiohbsantos/github-material-icons-extension)):
image

**Comment by GaryGSC** [comment]
Another tiny reason to rename `terraform-iac` to `terraform`: editors treat kebab-case as multiple "words" and so the directory name can't be selected by double-clicking.

**Review by jvisker — APPROVED** [review]

**Comment by GaryGSC** [comment]
Rebased on `dev`.

**Comment by GaryGSC** [comment]
Closing in favor of #1247.

**Pull request closed without merging**
