### PR TITLE
Use aws-sdk@v3 (broken down by service)

### LINKED ISSUE #213: Use v3 of the aws-sdk

### PR DESCRIPTION
**Pull request by GaryGSC**
I took out the `ignore` clause in the Dependabot config because these clients seem to get updated much less often.

Closes #213.

### CODE REVIEW

**Review by stuft2 — COMMENTED** [review]
I thought that aws-sdk@v3 required you to created a "Command" object for the request you wanted to make and then one would "send" the command. For example:

```ts
async function createBucket (logger: Logger, credentialProvider?: CredentialProvider): Promise<CreateBucketCommandOutput> {
  const bucketId = `aws-rds-pg-sync-${uuid()}`
  logger.info(`Creating S3 bucket ${bucketId}`)
  const client = new S3Client({
    ...credentialProvider && { credentials: credentialProvider }
  })
  const createBucketCommand = new CreateBucketCommand({ Bucket: bucketId })
  const result = await client.send(createBucketCommand)
  logger.info(`Created S3 bucket ${bucketId}`)
  return result
}
```

**Comment by GaryGSC** [comment]
That command style is their [suggested usage](https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-dynamodb#usage), but they also support a [v2 compatible style](https://github.com/aws/aws-sdk-js-v3/tree/main/clients/client-dynamodb#v2-compatible-style).

**Comment by GaryGSC** [comment]
Shall we switch this PR to the command syntax?

Pros:
- More tree-shakable, but we're not using `import` or a build process here right now
- Sounds like it's the direction AWS wants to take, if/when they release v4
- Performance?

Cons:
- Bigger diff in this PR
- Different, more verbose syntax than people are used to

(Feel free to add more)

**Comment by stuft2** [comment]
I would say yes because AWS doesn't guarantee support for v2 style in the next major version anyway. I'll make those changes.

**Review by stuft2 — APPROVED** [review]

**Comment by GaryGSC** [comment]
LGTM now.

**Pull request merged**
