### PR TITLE
Build and deploy ARM-based containers

### LINKED ISSUE #389: Build and deploy ARM-based containers
Now that ECS Fargate [supports ARM](https://aws.amazon.com/blogs/aws/announcing-aws-graviton2-support-for-aws-fargate-get-up-to-40-better-price-performance-for-your-serverless-containers/) containers, we can supposedly see 40 percent better price-performance at 20 percent lower cost. I believe all of the languages we're likely to use can compile to ARM, so Fargate support for ARM was our last remaining roadblock.

Taking a cursory look at the required steps, it'd involve:
- [x] Adding a [`docker/setup-qemu-action`](https://github.com/docker/setup-qemu-action) step so that the build environment can emulate ARM
- [x] Telling the `docker/build-push-action` step to build for ARM
- [x] Telling Fargate that we're deploying using ARM (It looks like a 1 line change to the task definition, but I imagine that'd require plumbing some configuration through one or more TF modules)

I'd like to think the overall impact to our build/deployment times should be small.

### PR DESCRIPTION
**Pull request by GaryGSC**
Depends on https://github.com/byu-oit/terraform-aws-fargate-api/pull/38, which I'm assuming will be released as `v5.0.0`.

Closes #389

### CODE REVIEW

**Review by stuft2 — APPROVED** [review]
LGTM ~~, maybe add a note in the README about the computer architecture and Oracle since I'm not sure everyone is downloading the binaries. [The Classes API has the binaries copied for example](https://github.com/byu-oit/byuapi-classes-v3/blob/dev/Dockerfile).~~

Nvm, this is just the hello world template, so they should download the right binaries if they're going to use oracle instant client.

**Comment by GaryGSC** [comment]
Correct. Check out [the linked issue](https://github.com/byu-oit/hw-fargate-api/issues/389) for more details. 🙂

**Comment by GaryGSC** [comment]
@stuft2 - We should document this, but I'm not sure where that belongs in the README.

**Comment by GaryGSC** [comment]
Once https://github.com/actions/runner-images/issues/5631 is resolved, we may be able to remove the QEMU step.

**Pull request merged**
